"use strict";
/**
 * @fileoverview gRPC-Web generated client stub for ToDoPackage
 * @enhanceable
 * @public
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TodoServiceClient = void 0;
// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: proto/todo.proto
/* eslint-disable */
// @ts-nocheck
var grpcWeb = __importStar(require("grpc-web"));
var proto_todo_pb = __importStar(require("../proto/todo_pb")); // proto import: "proto/todo.proto"
var TodoServiceClient = /** @class */ (function () {
    function TodoServiceClient(hostname, credentials, options) {
        this.methodDescriptorPingPong = new grpcWeb.MethodDescriptor('/ToDoPackage.TodoService/PingPong', grpcWeb.MethodType.UNARY, proto_todo_pb.PingRequest, proto_todo_pb.PongResponse, function (request) {
            return request.serializeBinary();
        }, proto_todo_pb.PongResponse.deserializeBinary);
        this.methodDescriptorCreate = new grpcWeb.MethodDescriptor('/ToDoPackage.TodoService/Create', grpcWeb.MethodType.UNARY, proto_todo_pb.Todo, proto_todo_pb.Todo, function (request) {
            return request.serializeBinary();
        }, proto_todo_pb.Todo.deserializeBinary);
        this.methodDescriptorReadAll = new grpcWeb.MethodDescriptor('/ToDoPackage.TodoService/ReadAll', grpcWeb.MethodType.UNARY, proto_todo_pb.GetTodo, proto_todo_pb.TodoList, function (request) {
            return request.serializeBinary();
        }, proto_todo_pb.TodoList.deserializeBinary);
        this.methodDescriptorUpdate = new grpcWeb.MethodDescriptor('/ToDoPackage.TodoService/Update', grpcWeb.MethodType.UNARY, proto_todo_pb.Todo, proto_todo_pb.Todo, function (request) {
            return request.serializeBinary();
        }, proto_todo_pb.Todo.deserializeBinary);
        this.methodDescriptorDelete = new grpcWeb.MethodDescriptor('/ToDoPackage.TodoService/Delete', grpcWeb.MethodType.UNARY, proto_todo_pb.TodoId, proto_todo_pb.Status, function (request) {
            return request.serializeBinary();
        }, proto_todo_pb.Status.deserializeBinary);
        if (!options)
            options = {};
        if (!credentials)
            credentials = {};
        options['format'] = 'text';
        this.client_ = new grpcWeb.GrpcWebClientBase(options);
        this.hostname_ = hostname.replace(/\/+$/, '');
        this.credentials_ = credentials;
        this.options_ = options;
    }
    TodoServiceClient.prototype.pingPong = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/ToDoPackage.TodoService/PingPong', request, metadata || {}, this.methodDescriptorPingPong, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/ToDoPackage.TodoService/PingPong', request, metadata || {}, this.methodDescriptorPingPong);
    };
    TodoServiceClient.prototype.create = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/ToDoPackage.TodoService/Create', request, metadata || {}, this.methodDescriptorCreate, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/ToDoPackage.TodoService/Create', request, metadata || {}, this.methodDescriptorCreate);
    };
    TodoServiceClient.prototype.readAll = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/ToDoPackage.TodoService/ReadAll', request, metadata || {}, this.methodDescriptorReadAll, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/ToDoPackage.TodoService/ReadAll', request, metadata || {}, this.methodDescriptorReadAll);
    };
    TodoServiceClient.prototype.update = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/ToDoPackage.TodoService/Update', request, metadata || {}, this.methodDescriptorUpdate, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/ToDoPackage.TodoService/Update', request, metadata || {}, this.methodDescriptorUpdate);
    };
    TodoServiceClient.prototype.delete = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/ToDoPackage.TodoService/Delete', request, metadata || {}, this.methodDescriptorDelete, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/ToDoPackage.TodoService/Delete', request, metadata || {}, this.methodDescriptorDelete);
    };
    return TodoServiceClient;
}());
exports.TodoServiceClient = TodoServiceClient;
