/**
 * @fileoverview gRPC-Web generated client stub for ToDoPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: proto/todo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_todo_pb from '../proto/todo_pb'; // proto import: "proto/todo.proto"


export class TodoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPingPong = new grpcWeb.MethodDescriptor(
    '/ToDoPackage.TodoService/PingPong',
    grpcWeb.MethodType.UNARY,
    proto_todo_pb.PingRequest,
    proto_todo_pb.PongResponse,
    (request: proto_todo_pb.PingRequest) => {
      return request.serializeBinary();
    },
    proto_todo_pb.PongResponse.deserializeBinary
  );

  pingPong(
    request: proto_todo_pb.PingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_todo_pb.PongResponse>;

  pingPong(
    request: proto_todo_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_todo_pb.PongResponse) => void): grpcWeb.ClientReadableStream<proto_todo_pb.PongResponse>;

  pingPong(
    request: proto_todo_pb.PingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_todo_pb.PongResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ToDoPackage.TodoService/PingPong',
        request,
        metadata || {},
        this.methodDescriptorPingPong,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ToDoPackage.TodoService/PingPong',
    request,
    metadata || {},
    this.methodDescriptorPingPong);
  }

  methodDescriptorCreate = new grpcWeb.MethodDescriptor(
    '/ToDoPackage.TodoService/Create',
    grpcWeb.MethodType.UNARY,
    proto_todo_pb.Todo,
    proto_todo_pb.Todo,
    (request: proto_todo_pb.Todo) => {
      return request.serializeBinary();
    },
    proto_todo_pb.Todo.deserializeBinary
  );

  create(
    request: proto_todo_pb.Todo,
    metadata?: grpcWeb.Metadata | null): Promise<proto_todo_pb.Todo>;

  create(
    request: proto_todo_pb.Todo,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Todo) => void): grpcWeb.ClientReadableStream<proto_todo_pb.Todo>;

  create(
    request: proto_todo_pb.Todo,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Todo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ToDoPackage.TodoService/Create',
        request,
        metadata || {},
        this.methodDescriptorCreate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ToDoPackage.TodoService/Create',
    request,
    metadata || {},
    this.methodDescriptorCreate);
  }

  methodDescriptorReadAll = new grpcWeb.MethodDescriptor(
    '/ToDoPackage.TodoService/ReadAll',
    grpcWeb.MethodType.UNARY,
    proto_todo_pb.GetTodo,
    proto_todo_pb.TodoList,
    (request: proto_todo_pb.GetTodo) => {
      return request.serializeBinary();
    },
    proto_todo_pb.TodoList.deserializeBinary
  );

  readAll(
    request: proto_todo_pb.GetTodo,
    metadata?: grpcWeb.Metadata | null): Promise<proto_todo_pb.TodoList>;

  readAll(
    request: proto_todo_pb.GetTodo,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_todo_pb.TodoList) => void): grpcWeb.ClientReadableStream<proto_todo_pb.TodoList>;

  readAll(
    request: proto_todo_pb.GetTodo,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_todo_pb.TodoList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ToDoPackage.TodoService/ReadAll',
        request,
        metadata || {},
        this.methodDescriptorReadAll,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ToDoPackage.TodoService/ReadAll',
    request,
    metadata || {},
    this.methodDescriptorReadAll);
  }

  methodDescriptorUpdate = new grpcWeb.MethodDescriptor(
    '/ToDoPackage.TodoService/Update',
    grpcWeb.MethodType.UNARY,
    proto_todo_pb.Todo,
    proto_todo_pb.Todo,
    (request: proto_todo_pb.Todo) => {
      return request.serializeBinary();
    },
    proto_todo_pb.Todo.deserializeBinary
  );

  update(
    request: proto_todo_pb.Todo,
    metadata?: grpcWeb.Metadata | null): Promise<proto_todo_pb.Todo>;

  update(
    request: proto_todo_pb.Todo,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Todo) => void): grpcWeb.ClientReadableStream<proto_todo_pb.Todo>;

  update(
    request: proto_todo_pb.Todo,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Todo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ToDoPackage.TodoService/Update',
        request,
        metadata || {},
        this.methodDescriptorUpdate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ToDoPackage.TodoService/Update',
    request,
    metadata || {},
    this.methodDescriptorUpdate);
  }

  methodDescriptorDelete = new grpcWeb.MethodDescriptor(
    '/ToDoPackage.TodoService/Delete',
    grpcWeb.MethodType.UNARY,
    proto_todo_pb.TodoId,
    proto_todo_pb.Status,
    (request: proto_todo_pb.TodoId) => {
      return request.serializeBinary();
    },
    proto_todo_pb.Status.deserializeBinary
  );

  delete(
    request: proto_todo_pb.TodoId,
    metadata?: grpcWeb.Metadata | null): Promise<proto_todo_pb.Status>;

  delete(
    request: proto_todo_pb.TodoId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Status) => void): grpcWeb.ClientReadableStream<proto_todo_pb.Status>;

  delete(
    request: proto_todo_pb.TodoId,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_todo_pb.Status) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ToDoPackage.TodoService/Delete',
        request,
        metadata || {},
        this.methodDescriptorDelete,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ToDoPackage.TodoService/Delete',
    request,
    metadata || {},
    this.methodDescriptorDelete);
  }

}

